name: Check source code

on:
  push:
    branches: [ "main" ]

  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_source_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check source code
        run: cargo clippy --all-targets --locked -- -D warnings

      - name: Run tests
        run: cargo test --locked
